### ISSUE TITLE
Some continuity issues with the CSS

### ISSUE THREAD

**Issue by samazsder** [amith2368/attendance-app#1]
Use #bfb3c2 for the text (except for the ones inside buttons)
For the background buttons, use #55345d -- borders: none; --
Also please update the card body divisions (eg. in the Register page) to be rgba(255,255,255,0.05) <- For semi transparency...

Please try to keep the color scheme uniform throughout.
Good job, btw! #:+1:

**Comment by amith2368** [comment]
### Changes / Modifications for login/register pages

- Changed the CSS properties for the font colours and button backgrounds
- Created the semi-transparent bg for the register card body
